### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by ceesvanegmond** [KarthikMAM/Kissanime-Download-Links-Grabber#1]
I get the follow error code with kissasian. Any idea?

![schermafbeelding 2016-03-26 om 00 20 04](https://cloud.githubusercontent.com/assets/883497/14056150/9e721dbe-f2e8-11e5-8342-52a42eed468b.png)

**Comment by KarthikMAM** [comment]
<b>Possible reasons</b>
- It seems that you are probably using an <b>older version</b> of this extension. This is because the site keeps changing its DOM model, so you need to have an updated version always.
- Next, the error "Uncaught: TypeError...." is due to error in the site's script and doesn't really have anything to do with the extension.

@ceesvanegmond download the latest version from <a href="https://github.com/KarthikMAM/Kissanime-Download-Links-Grabber/releases/download/v1.11/Kissanime-Download-Links-Grabber.crx">here</a>. If you still have any issues please do notify me.
